name: Format Code

on:
  push:
    branches:
      - main # Change this to your main branch name
  pull_request:
    branches:
      - main # Change this to your main branch name

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Format code
        run: yarn format

      - name: Commit formatted code
        run: |
          git config --local user.email "cheng-alvin@users.noreply.github.com"
          git config --local user.name "Alvin cheng"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Format code with Prettier"
          git push
